# Generated by Django 4.2.3 on 2023-07-19 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickit', '0003_show_delete_shows'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='poster',
            field=models.TextField(default='No Poster Provided'),
        ),
        migrations.AddField(
            model_name='show',
            name='starting_price',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='show',
            name='time',
            field=models.CharField(default='12:00pm', max_length=100),
        ),
        migrations.AddField(
            model_name='show',
            name='title',
            field=models.CharField(default='No Title Available', max_length=100),
        ),
        migrations.AddField(
            model_name='show',
            name='venue_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='show', to='tickit.venue'),
        ),
        migrations.AlterField(
            model_name='show',
            name='show_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='venue',
            name='venue_photo',
            field=models.TextField(default='No photo available'),
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('logo', models.TextField(default='No Logo Provided')),
                ('show_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='band', to='tickit.show')),
            ],
        ),
    ]
