# Generated by Django 4.2.3 on 2023-07-19 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickit', '0004_show_poster_show_starting_price_show_time_show_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='show_id',
        ),
        migrations.AddField(
            model_name='show',
            name='band_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='band', to='tickit.band'),
        ),
        migrations.AlterField(
            model_name='band',
            name='band_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='band',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='show',
            name='venue_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='venue', to='tickit.venue'),
        ),
    ]
