# Generated by Django 4.2.3 on 2023-07-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickit', '0006_alter_band_logo_alter_show_poster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='logo',
            field=models.CharField(default='No Logo Provided'),
        ),
        migrations.AlterField(
            model_name='show',
            name='poster',
            field=models.CharField(default='No Poster Provided'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='venue_photo',
            field=models.CharField(default='No photo available'),
        ),
    ]
